package com.eu.foxgames.dto

/**
 * Data transfer object (DTO) representing the GameForm information received from Twitch.
 *
 * This class is used to transfer the GameForm information (all the information)
 */
data class GameForm(
    val age_ratings: List<String>,
    val aggregated_rating: Double,
    val aggregated_rating_count: Int,
    val alternative_names: List<String>,
    val artworks: List<String>,
    val bundles: List<String>,
    val category: String,
    val checksum: String,
    val collection: Long,
    val collections: List<String>,
    val cover: Long,
    val created_at: Long,
    val dlcs: List<String>,
    val expanded_games: List<String>,
    val expansions: List<String>,
    val external_games: List<String>,
    val first_release_date: Long,
    val follows: Int,
    val forks: String,
    val franchise: Long,
    val franchises: List<String>,
    val game_engines: List<String>,
    val game_localizations: List<String>,
    val game_modes: List<String>,
    val genres: List<String>,
    val hypes: Int,
    val involved_companies: List<String>,
    val keywords: List<String>,
    val language_supports: List<String>,
    val multiplayer_modes: List<String>,
    val name: String,
    val parent_game: String,
    val platforms: List<String>,
    val player_perspectives: List<String>,
    val ports: List<String>,
    val rating: Double,
    val rating_count: Int,
    val release_dates: List<Long>,
    val remakes: List<String>,
    val remasters: List<String>,
    val screenshots: List<String>,
    val similar_games: List<String>,
    val slug: String,
    val standalone_expansions: List<String>,
    val status: String,
    val storyline: String,
    val summary: String,
    val tags: List<String>,
    val themes: List<String>,
    val total_rating: Double,
    val total_rating_count: Int,
    val updated_at: Long,
    val url: String,
    val version_parent: Long,
    val version_title: String,
    val videos: List<String>,
    val websites:List<String>,
)
