spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:foxgames
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enable: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
