CREATE TABLE tb_role (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO tb_role(id, name) VALUES(1, 'ADMIN_ROLE');
INSERT INTO tb_role(id, name) VALUES(2, 'NORMAL_USER_ROLE');
